/* automatically generated from xfce4-about-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfce_about_dialog_ui)
#endif
#ifdef __GNUC__
static const char xfce_about_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce_about_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.16"
  "\"/><object class=\"XfceTitledDialog\" id=\"window\"><property name=\"t"
  "itle\" translatable=\"yes\">About the Xfce Desktop Environment</propert"
  "y><property name=\"default_width\">500</property><property name=\"defau"
  "lt_height\">400</property><property name=\"icon_name\">xfce4-logo</prop"
  "erty><property name=\"type_hint\">normal</property><child internal-chil"
  "d=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><property name"
  "=\"visible\">True</property><property name=\"orientation\">vertical</pr"
  "operty><property name=\"spacing\">2</property><child><object class=\"Gt"
  "kNotebook\" id=\"notebook\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"border_widt"
  "h\">6</property><child><object class=\"GtkScrolledWindow\" id=\"scrolle"
  "dwindow1\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"border_width\">6</property><"
  "property name=\"hscrollbar_policy\">automatic</property><property name="
  "\"vscrollbar_policy\">automatic</property><property name=\"shadow_type\""
  ">etched-in</property><child><object class=\"GtkTextView\" id=\"about-te"
  "xtview\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"editable\">False</property><pr"
  "operty name=\"wrap_mode\">word</property><property name=\"left_margin\""
  ">3</property><property name=\"right_margin\">3</property><property name"
  "=\"cursor_visible\">False</property><property name=\"buffer\">about-buf"
  "fer</property></object></child></object></child><child type=\"tab\"><ob"
  "ject class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</"
  "property><property name=\"label\" translatable=\"yes\">About</property>"
  "</object><packing><property name=\"tab_fill\">False</property></packing"
  "></child><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindow"
  "2\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"border_width\">6</property><propert"
  "y name=\"hscrollbar_policy\">automatic</property><property name=\"vscro"
  "llbar_policy\">automatic</property><property name=\"shadow_type\">etche"
  "d-in</property><child><object class=\"GtkTextView\" id=\"credits-textvi"
  "ew\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"editable\">False</property><proper"
  "ty name=\"wrap_mode\">word</property><property name=\"left_margin\">3</"
  "property><property name=\"right_margin\">3</property><property name=\"c"
  "ursor_visible\">False</property><property name=\"buffer\">credits-buffe"
  "r</property></object></child></object><packing><property name=\"positio"
  "n\">1</property></packing></child><child type=\"tab\"><object class=\"G"
  "tkLabel\" id=\"label2\"><property name=\"visible\">True</property><prop"
  "erty name=\"label\" translatable=\"yes\">Credits</property></object><pa"
  "cking><property name=\"position\">1</property><property name=\"tab_fill"
  "\">False</property></packing></child><child><object class=\"GtkScrolled"
  "Window\" id=\"vendor-tab\"><property name=\"can_focus\">True</property>"
  "<property name=\"border_width\">6</property><property name=\"hscrollbar"
  "_policy\">automatic</property><property name=\"vscrollbar_policy\">auto"
  "matic</property><property name=\"shadow_type\">etched-in</property><chi"
  "ld><object class=\"GtkTextView\" id=\"vendor-textview\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"editable\">False</property><property name=\"wrap_mode\""
  ">word</property><property name=\"left_margin\">3</property><property na"
  "me=\"right_margin\">3</property><property name=\"cursor_visible\">False"
  "</property><property name=\"buffer\">vendor-buffer</property></object><"
  "/child></object><packing><property name=\"position\">2</property></pack"
  "ing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"vendor-"
  "label\"><property name=\"visible\">True</property><property name=\"labe"
  "l\">Vendor</property></object><packing><property name=\"position\">2</p"
  "roperty><property name=\"tab_fill\">False</property></packing></child><"
  "child><object class=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\""
  ">True</property><property name=\"border_width\">6</property><property n"
  "ame=\"orientation\">vertical</property><property name=\"spacing\">6</pr"
  "operty><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindow3\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"hscrollbar_policy\">automatic</propert"
  "y><property name=\"vscrollbar_policy\">automatic</property><property na"
  "me=\"shadow_type\">etched-in</property><child><object class=\"GtkTextVi"
  "ew\" id=\"copyright-textview\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"editable"
  "\">False</property><property name=\"wrap_mode\">word</property><propert"
  "y name=\"left_margin\">3</property><property name=\"right_margin\">3</p"
  "roperty><property name=\"cursor_visible\">False</property><property nam"
  "e=\"buffer\">copyright-buffer</property></object></child></object><pack"
  "ing><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkHButtonBox\" id=\"hbuttonbox1\"><property name=\"visib"
  "le\">True</property><property name=\"spacing\">6</property><property na"
  "me=\"layout_style\">start</property><child><object class=\"GtkButton\" "
  "id=\"gpl-button\"><property name=\"label\" translatable=\"yes\">GPL</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkButton\" id=\"lgpl-button\""
  "><property name=\"label\" translatable=\"yes\">LGPL</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">1</property></packing></chil"
  "d><child><object class=\"GtkButton\" id=\"bsd-button\"><property name=\""
  "label\" translatable=\"yes\">BSD</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">2</property></packing></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"position\">"
  "1</property></packing></child></object><packing><property name=\"positi"
  "on\">3</property></packing></child><child type=\"tab\"><object class=\""
  "GtkLabel\" id=\"label3\"><property name=\"visible\">True</property><pro"
  "perty name=\"label\" translatable=\"yes\">Copyright</property></object>"
  "<packing><property name=\"position\">3</property><property name=\"tab_f"
  "ill\">False</property></packing></child></object><packing><property nam"
  "e=\"position\">1</property></packing></child><child internal-child=\"ac"
  "tion_area\"><object class=\"GtkHButtonBox\" id=\"dialog-action_area1\">"
  "<property name=\"visible\">True</property><property name=\"layout_style"
  "\">end</property><child><object class=\"GtkButton\" id=\"help-button\">"
  "<property name=\"label\">gtk-help</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">True</property><property name=\"use_stock\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">0<"
  "/property><property name=\"secondary\">True</property></packing></child"
  "><child><object class=\"GtkButton\" id=\"close-button\"><property name="
  "\"label\">gtk-close</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">True</property><property name=\"use_stock\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">1</property></pa"
  "cking></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"pack_type\">end</property><property name=\"position"
  "\">0</property></packing></child></object></child><action-widgets><acti"
  "on-widget response=\"0\">help-button</action-widget><action-widget resp"
  "onse=\"0\">close-button</action-widget></action-widgets></object><objec"
  "t class=\"GtkDialog\" id=\"license-dialog\"><property name=\"border_wid"
  "th\">5</property><property name=\"title\" translatable=\"yes\">License<"
  "/property><property name=\"modal\">True</property><property name=\"defa"
  "ult_width\">500</property><property name=\"default_height\">300</proper"
  "ty><property name=\"type_hint\">normal</property><child internal-child="
  "\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox2\"><property name=\""
  "visible\">True</property><property name=\"orientation\">vertical</prope"
  "rty><property name=\"spacing\">2</property><child><object class=\"GtkSc"
  "rolledWindow\" id=\"scrolledwindow4\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"b"
  "order_width\">6</property><property name=\"hscrollbar_policy\">automati"
  "c</property><property name=\"vscrollbar_policy\">automatic</property><p"
  "roperty name=\"shadow_type\">etched-in</property><child><object class=\""
  "GtkTextView\" id=\"license-textview\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"e"
  "ditable\">False</property><property name=\"wrap_mode\">word</property><"
  "property name=\"justification\">center</property><property name=\"left_"
  "margin\">3</property><property name=\"right_margin\">3</property><prope"
  "rty name=\"cursor_visible\">False</property></object></child></object><"
  "packing><property name=\"position\">1</property></packing></child><chil"
  "d internal-child=\"action_area\"><object class=\"GtkHButtonBox\" id=\"d"
  "ialog-action_area2\"><property name=\"visible\">True</property><propert"
  "y name=\"layout_style\">end</property><child><object class=\"GtkButton\""
  " id=\"license-close-button\"><property name=\"label\">gtk-close</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">True</property><p"
  "roperty name=\"use_stock\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">0</property></packing></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"pack_ty"
  "pe\">end</property><property name=\"position\">0</property></packing></"
  "child></object></child><action-widgets><action-widget response=\"0\">li"
  "cense-close-button</action-widget></action-widgets></object><object cla"
  "ss=\"GtkTextBuffer\" id=\"about-buffer\"/><object class=\"GtkTextBuffer"
  "\" id=\"credits-buffer\"/><object class=\"GtkTextBuffer\" id=\"copyrigh"
  "t-buffer\"/><object class=\"GtkTextBuffer\" id=\"gpl-buffer\"><property"
  " name=\"text\">GNU GENERAL PUBLIC LICENSE\n\nVersion 2, June 1991\n\nCo"
  "pyright (C) 1989, 1991 Free Software Foundation, Inc.  \n51 Franklin St"
  "reet, Fifth Floor, Boston, MA  02110-1301, USA\n\nEveryone is permitted"
  " to copy and distribute verbatim copies of this license document, but c"
  "hanging it is not allowed.\n\nPreamble\n\nThe licenses for most softwar"
  "e are designed to take away your freedom to share and change it. By con"
  "trast, the GNU General Public License is intended to guarantee your fre"
  "edom to share and change free software--to make sure the software is fr"
  "ee for all its users. This General Public License applies to most of th"
  "e Free Software Foundation\'s software and to any other program whose a"
  "uthors commit to using it. (Some other Free Software Foundation softwar"
  "e is covered by the GNU Lesser General Public License instead.) You can"
  " apply it to your programs, too.\n\nWhen we speak of free software, we "
  "are referring to freedom, not price. Our General Public Licenses are de"
  "signed to make sure that you have the freedom to distribute copies of f"
  "ree software (and charge for this service if you wish), that you receiv"
  "e source code or can get it if you want it, that you can change the sof"
  "tware or use pieces of it in new free programs; and that you know you c"
  "an do these things.\n\nTo protect your rights, we need to make restrict"
  "ions that forbid anyone to deny you these rights or to ask you to surre"
  "nder the rights. These restrictions translate to certain responsibiliti"
  "es for you if you distribute copies of the software, or if you modify i"
  "t.\n\nFor example, if you distribute copies of such a program, whether "
  "gratis or for a fee, you must give the recipients all the rights that y"
  "ou have. You must make sure that they, too, receive or can get the sour"
  "ce code. And you must show them these terms so they know their rights.\n"
  "\nWe protect your rights with two steps: (1) copyright the software, an"
  "d (2) offer you this license which gives you legal permission to copy, "
  "distribute and/or modify the software.\n\nAlso, for each author\'s prot"
  "ection and ours, we want to make certain that everyone understands that"
  " there is no warranty for this free software. If the software is modifi"
  "ed by someone else and passed on, we want its recipients to know that w"
  "hat they have is not the original, so that any problems introduced by o"
  "thers will not reflect on the original authors\' reputations.\n\nFinall"
  "y, any free program is threatened constantly by software patents. We wi"
  "sh to avoid the danger that redistributors of a free program will indiv"
  "idually obtain patent licenses, in effect making the program proprietar"
  "y. To prevent this, we have made it clear that any patent must be licen"
  "sed for everyone\'s free use or not licensed at all.\n\nThe precise ter"
  "ms and conditions for copying, distribution and modification follow.\nT"
  "ERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n0. Th"
  "is License applies to any program or other work which contains a notice"
  " placed by the copyright holder saying it may be distributed under the "
  "terms of this General Public License. The \"Program\", below, refers to"
  " any such program or work, and a \"work based on the Program\" means ei"
  "ther the Program or any derivative work under copyright law: that is to"
  " say, a work containing the Program or a portion of it, either verbatim"
  " or with modifications and/or translated into another language. (Herein"
  "after, translation is included without limitation in the term \"modific"
  "ation\".) Each licensee is addressed as \"you\".\n\nActivities other th"
  "an copying, distribution and modification are not covered by this Licen"
  "se; they are outside its scope. The act of running the Program is not r"
  "estricted, and the output from the Program is covered only if its conte"
  "nts constitute a work based on the Program (independent of having been "
  "made by running the Program). Whether that is true depends on what the "
  "Program does.\n\n1. You may copy and distribute verbatim copies of the "
  "Program\'s source code as you receive it, in any medium, provided that "
  "you conspicuously and appropriately publish on each copy an appropriate"
  " copyright notice and disclaimer of warranty; keep intact all the notic"
  "es that refer to this License and to the absence of any warranty; and g"
  "ive any other recipients of the Program a copy of this License along wi"
  "th the Program.\n\nYou may charge a fee for the physical act of transfe"
  "rring a copy, and you may at your option offer warranty protection in e"
  "xchange for a fee.\n\n2. You may modify your copy or copies of the Prog"
  "ram or any portion of it, thus forming a work based on the Program, and"
  " copy and distribute such modifications or work under the terms of Sect"
  "ion 1 above, provided that you also meet all of these conditions:\n\n  "
  "  a) You must cause the modified files to carry prominent notices stati"
  "ng that you changed the files and the date of any change. \n    b) You "
  "must cause any work that you distribute or publish, that in whole or in"
  " part contains or is derived from the Program or any part thereof, to b"
  "e licensed as a whole at no charge to all third parties under the terms"
  " of this License. \n    c) If the modified program normally reads comma"
  "nds interactively when run, you must cause it, when started running for"
  " such interactive use in the most ordinary way, to print or display an "
  "announcement including an appropriate copyright notice and a notice tha"
  "t there is no warranty (or else, saying that you provide a warranty) an"
  "d that users may redistribute the program under these conditions, and t"
  "elling the user how to view a copy of this License. (Exception: if the "
  "Program itself is interactive but does not normally print such an annou"
  "ncement, your work based on the Program is not required to print an ann"
  "ouncement.) \n\nThese requirements apply to the modified work as a whol"
  "e. If identifiable sections of that work are not derived from the Progr"
  "am, and can be reasonably considered independent and separate works in "
  "themselves, then this License, and its terms, do not apply to those sec"
  "tions when you distribute them as separate works. But when you distribu"
  "te the same sections as part of a whole which is a work based on the Pr"
  "ogram, the distribution of the whole must be on the terms of this Licen"
  "se, whose permissions for other licensees extend to the entire whole, a"
  "nd thus to each and every part regardless of who wrote it.\n\nThus, it "
  "is not the intent of this section to claim rights or contest your right"
  "s to work written entirely by you; rather, the intent is to exercise th"
  "e right to control the distribution of derivative or collective works b"
  "ased on the Program.\n\nIn addition, mere aggregation of another work n"
  "ot based on the Program with the Program (or with a work based on the P"
  "rogram) on a volume of a storage or distribution medium does not bring "
  "the other work under the scope of this License.\n\n3. You may copy and "
  "distribute the Program (or a work based on it, under Section 2) in obje"
  "ct code or executable form under the terms of Sections 1 and 2 above pr"
  "ovided that you also do one of the following:\n\n    a) Accompany it wi"
  "th the complete corresponding machine-readable source code, which must "
  "be distributed under the terms of Sections 1 and 2 above on a medium cu"
  "stomarily used for software interchange; or, \n    b) Accompany it with"
  " a written offer, valid for at least three years, to give any third par"
  "ty, for a charge no more than your cost of physically performing source"
  " distribution, a complete machine-readable copy of the corresponding so"
  "urce code, to be distributed under the terms of Sections 1 and 2 above "
  "on a medium customarily used for software interchange; or, \n    c) Acc"
  "ompany it with the information you received as to the offer to distribu"
  "te corresponding source code. (This alternative is allowed only for non"
  "commercial distribution and only if you received the program in object "
  "code or executable form with such an offer, in accord with Subsection b"
  " above.) \n\nThe source code for a work means the preferred form of the"
  " work for making modifications to it. For an executable work, complete "
  "source code means all the source code for all modules it contains, plus"
  " any associated interface definition files, plus the scripts used to co"
  "ntrol compilation and installation of the executable. However, as a spe"
  "cial exception, the source code distributed need not include anything t"
  "hat is normally distributed (in either source or binary form) with the "
  "major components (compiler, kernel, and so on) of the operating system "
  "on which the executable runs, unless that component itself accompanies "
  "the executable.\n\nIf distribution of executable or object code is made"
  " by offering access to copy from a designated place, then offering equi"
  "valent access to copy the source code from the same place counts as dis"
  "tribution of the source code, even though third parties are not compell"
  "ed to copy the source along with the object code.\n\n4. You may not cop"
  "y, modify, sublicense, or distribute the Program except as expressly pr"
  "ovided under this License. Any attempt otherwise to copy, modify, subli"
  "cense or distribute the Program is void, and will automatically termina"
  "te your rights under this License. However, parties who have received c"
  "opies, or rights, from you under this License will not have their licen"
  "ses terminated so long as such parties remain in full compliance.\n\n5."
  " You are not required to accept this License, since you have not signed"
  " it. However, nothing else grants you permission to modify or distribut"
  "e the Program or its derivative works. These actions are prohibited by "
  "law if you do not accept this License. Therefore, by modifying or distr"
  "ibuting the Program (or any work based on the Program), you indicate yo"
  "ur acceptance of this License to do so, and all its terms and condition"
  "s for copying, distributing or modifying the Program or works based on "
  "it.\n\n6. Each time you redistribute the Program (or any work based on "
  "the Program), the recipient automatically receives a license from the o"
  "riginal licensor to copy, distribute or modify the Program subject to t"
  "hese terms and conditions. You may not impose any further restrictions "
  "on the recipients\' exercise of the rights granted herein. You are not "
  "responsible for enforcing compliance by third parties to this License.\n"
  "\n7. If, as a consequence of a court judgment or allegation of patent i"
  "nfringement or for any other reason (not limited to patent issues), con"
  "ditions are imposed on you (whether by court order, agreement or otherw"
  "ise) that contradict the conditions of this License, they do not excuse"
  " you from the conditions of this License. If you cannot distribute so a"
  "s to satisfy simultaneously your obligations under this License and any"
  " other pertinent obligations, then as a consequence you may not distrib"
  "ute the Program at all. For example, if a patent license would not perm"
  "it royalty-free redistribution of the Program by all those who receive "
  "copies directly or indirectly through you, then the only way you could "
  "satisfy both it and this License would be to refrain entirely from dist"
  "ribution of the Program.\n\nIf any portion of this section is held inva"
  "lid or unenforceable under any particular circumstance, the balance of "
  "the section is intended to apply and the section as a whole is intended"
  " to apply in other circumstances.\n\nIt is not the purpose of this sect"
  "ion to induce you to infringe any patents or other property right claim"
  "s or to contest validity of any such claims; this section has the sole "
  "purpose of protecting the integrity of the free software distribution s"
  "ystem, which is implemented by public license practices. Many people ha"
  "ve made generous contributions to the wide range of software distribute"
  "d through that system in reliance on consistent application of that sys"
  "tem; it is up to the author/donor to decide if he or she is willing to "
  "distribute software through any other system and a licensee cannot impo"
  "se that choice.\n\nThis section is intended to make thoroughly clear wh"
  "at is believed to be a consequence of the rest of this License.\n\n8. I"
  "f the distribution and/or use of the Program is restricted in certain c"
  "ountries either by patents or by copyrighted interfaces, the original c"
  "opyright holder who places the Program under this License may add an ex"
  "plicit geographical distribution limitation excluding those countries, "
  "so that distribution is permitted only in or among countries not thus e"
  "xcluded. In such case, this License incorporates the limitation as if w"
  "ritten in the body of this License.\n\n9. The Free Software Foundation "
  "may publish revised and/or new versions of the General Public License f"
  "rom time to time. Such new versions will be similar in spirit to the pr"
  "esent version, but may differ in detail to address new problems or conc"
  "erns.\n\nEach version is given a distinguishing version number. If the "
  "Program specifies a version number of this License which applies to it "
  "and \"any later version\", you have the option of following the terms a"
  "nd conditions either of that version or of any later version published "
  "by the Free Software Foundation. If the Program does not specify a vers"
  "ion number of this License, you may choose any version ever published b"
  "y the Free Software Foundation.\n\n10. If you wish to incorporate parts"
  " of the Program into other free programs whose distribution conditions "
  "are different, write to the author to ask for permission. For software "
  "which is copyrighted by the Free Software Foundation, write to the Free"
  " Software Foundation; we sometimes make exceptions for this. Our decisi"
  "on will be guided by the two goals of preserving the free status of all"
  " derivatives of our free software and of promoting the sharing and reus"
  "e of software generally.\n\nNO WARRANTY\n\n11. BECAUSE THE PROGRAM IS L"
  "ICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EX"
  "TENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITI"
  "NG THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS "
  "IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDI"
  "NG, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND F"
  "ITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND "
  "PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECT"
  "IVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTI"
  "ON.\n\n12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO I"
  "N WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY "
  "AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FO"
  "R DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL "
  "DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDI"
  "NG BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR"
  " LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM T"
  "O OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY "
  "HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </property></objec"
  "t><object class=\"GtkTextBuffer\" id=\"lgpl-buffer\"><property name=\"t"
  "ext\">GNU LIBRARY GENERAL PUBLIC LICENSE\n\nVersion 2, June 1991\n\nCop"
  "yright (C) 1991 Free Software Foundation, Inc.\n51 Franklin St, Fifth F"
  "loor, Boston, MA  02110-1301, USA\n\nEveryone is permitted to copy and "
  "distribute verbatim copies of this license document, but changing it is"
  " not allowed.\n\n[This is the first released version of the library GPL"
  ". It is numbered 2 because it goes with version 2 of the ordinary GPL.]"
  "\n\nPreamble\n\nThe licenses for most software are designed to take awa"
  "y your freedom to share and change it. By contrast, the GNU General Pub"
  "lic Licenses are intended to guarantee your freedom to share and change"
  " free software--to make sure the software is free for all its users.\n\n"
  "This license, the Library General Public License, applies to some speci"
  "ally designated Free Software Foundation software, and to any other lib"
  "raries whose authors decide to use it. You can use it for your librarie"
  "s, too.\n\nWhen we speak of free software, we are referring to freedom,"
  " not price. Our General Public Licenses are designed to make sure that "
  "you have the freedom to distribute copies of free software (and charge "
  "for this service if you wish), that you receive source code or can get "
  "it if you want it, that you can change the software or use pieces of it"
  " in new free programs; and that you know you can do these things.\n\nTo"
  " protect your rights, we need to make restrictions that forbid anyone t"
  "o deny you these rights or to ask you to surrender the rights. These re"
  "strictions translate to certain responsibilities for you if you distrib"
  "ute copies of the library, or if you modify it.\n\nFor example, if you "
  "distribute copies of the library, whether gratis or for a fee, you must"
  " give the recipients all the rights that we gave you. You must make sur"
  "e that they, too, receive or can get the source code. If you link a pro"
  "gram with the library, you must provide complete object files to the re"
  "cipients so that they can relink them with the library, after making ch"
  "anges to the library and recompiling it. And you must show them these t"
  "erms so they know their rights.\n\nOur method of protecting your rights"
  " has two steps: (1) copyright the library, and (2) offer you this licen"
  "se which gives you legal permission to copy, distribute and/or modify t"
  "he library.\n\nAlso, for each distributor\'s protection, we want to mak"
  "e certain that everyone understands that there is no warranty for this "
  "free library. If the library is modified by someone else and passed on,"
  " we want its recipients to know that what they have is not the original"
  " version, so that any problems introduced by others will not reflect on"
  " the original authors\' reputations.\n\nFinally, any free program is th"
  "reatened constantly by software patents. We wish to avoid the danger th"
  "at companies distributing free software will individually obtain patent"
  " licenses, thus in effect transforming the program into proprietary sof"
  "tware. To prevent this, we have made it clear that any patent must be l"
  "icensed for everyone\'s free use or not licensed at all.\n\nMost GNU so"
  "ftware, including some libraries, is covered by the ordinary GNU Genera"
  "l Public License, which was designed for utility programs. This license"
  ", the GNU Library General Public License, applies to certain designated"
  " libraries. This license is quite different from the ordinary one; be s"
  "ure to read it in full, and don\'t assume that anything in it is the sa"
  "me as in the ordinary license.\n\nThe reason we have a separate public "
  "license for some libraries is that they blur the distinction we usually"
  " make between modifying or adding to a program and simply using it. Lin"
  "king a program with a library, without changing the library, is in some"
  " sense simply using the library, and is analogous to running a utility "
  "program or application program. However, in a textual and legal sense, "
  "the linked executable is a combined work, a derivative of the original "
  "library, and the ordinary General Public License treats it as such.\n\n"
  "Because of this blurred distinction, using the ordinary General Public "
  "License for libraries did not effectively promote software sharing, bec"
  "ause most developers did not use the libraries. We concluded that weake"
  "r conditions might promote sharing better.\n\nHowever, unrestricted lin"
  "king of non-free programs would deprive the users of those programs of "
  "all benefit from the free status of the libraries themselves. This Libr"
  "ary General Public License is intended to permit developers of non-free"
  " programs to use free libraries, while preserving your freedom as a use"
  "r of such programs to change the free libraries that are incorporated i"
  "n them. (We have not seen how to achieve this as regards changes in hea"
  "der files, but we have achieved it as regards changes in the actual fun"
  "ctions of the Library.) The hope is that this will lead to faster devel"
  "opment of free libraries.\n\nThe precise terms and conditions for copyi"
  "ng, distribution and modification follow. Pay close attention to the di"
  "fference between a \"work based on the library\" and a \"work that uses"
  " the library\". The former contains code derived from the library, whil"
  "e the latter only works together with the library.\n\nNote that it is p"
  "ossible for a library to be covered by the ordinary General Public Lice"
  "nse rather than by this special one.\nTERMS AND CONDITIONS FOR COPYING,"
  " DISTRIBUTION AND MODIFICATION\n\n0. This License Agreement applies to "
  "any software library which contains a notice placed by the copyright ho"
  "lder or other authorized party saying it may be distributed under the t"
  "erms of this Library General Public License (also called \"this License"
  "\"). Each licensee is addressed as \"you\".\n\nA \"library\" means a co"
  "llection of software functions and/or data prepared so as to be conveni"
  "ently linked with application programs (which use some of those functio"
  "ns and data) to form executables.\n\nThe \"Library\", below, refers to "
  "any such software library or work which has been distributed under thes"
  "e terms. A \"work based on the Library\" means either the Library or an"
  "y derivative work under copyright law: that is to say, a work containin"
  "g the Library or a portion of it, either verbatim or with modifications"
  " and/or translated straightforwardly into another language. (Hereinafte"
  "r, translation is included without limitation in the term \"modificatio"
  "n\".)\n\n\"Source code\" for a work means the preferred form of the wor"
  "k for making modifications to it. For a library, complete source code m"
  "eans all the source code for all modules it contains, plus any associat"
  "ed interface definition files, plus the scripts used to control compila"
  "tion and installation of the library.\n\nActivities other than copying,"
  " distribution and modification are not covered by this License; they ar"
  "e outside its scope. The act of running a program using the Library is "
  "not restricted, and output from such a program is covered only if its c"
  "ontents constitute a work based on the Library (independent of the use "
  "of the Library in a tool for writing it). Whether that is true depends "
  "on what the Library does and what the program that uses the Library doe"
  "s.\n\n1. You may copy and distribute verbatim copies of the Library\'s "
  "complete source code as you receive it, in any medium, provided that yo"
  "u conspicuously and appropriately publish on each copy an appropriate c"
  "opyright notice and disclaimer of warranty; keep intact all the notices"
  " that refer to this License and to the absence of any warranty; and dis"
  "tribute a copy of this License along with the Library.\n\nYou may charg"
  "e a fee for the physical act of transferring a copy, and you may at you"
  "r option offer warranty protection in exchange for a fee.\n\n2. You may"
  " modify your copy or copies of the Library or any portion of it, thus f"
  "orming a work based on the Library, and copy and distribute such modifi"
  "cations or work under the terms of Section 1 above, provided that you a"
  "lso meet all of these conditions:\n\n    * a) The modified work must it"
  "self be a software library.\n    * b) You must cause the files modified"
  " to carry prominent notices stating that you changed the files and the "
  "date of any change.\n    * c) You must cause the whole of the work to b"
  "e licensed at no charge to all third parties under the terms of this Li"
  "cense.\n    * d) If a facility in the modified Library refers to a func"
  "tion or a table of data to be supplied by an application program that u"
  "ses the facility, other than as an argument passed when the facility is"
  " invoked, then you must make a good faith effort to ensure that, in the"
  " event an application does not supply such function or table, the facil"
  "ity still operates, and performs whatever part of its purpose remains m"
  "eaningful.\n\n      (For example, a function in a library to compute sq"
  "uare roots has a purpose that is entirely well-defined independent of t"
  "he application. Therefore, Subsection 2d requires that any application-"
  "supplied function or table used by this function must be optional: if t"
  "he application does not supply it, the square root function must still "
  "compute square roots.)\n\nThese requirements apply to the modified work"
  " as a whole. If identifiable sections of that work are not derived from"
  " the Library, and can be reasonably considered independent and separate"
  " works in themselves, then this License, and its terms, do not apply to"
  " those sections when you distribute them as separate works. But when yo"
  "u distribute the same sections as part of a whole which is a work based"
  " on the Library, the distribution of the whole must be on the terms of "
  "this License, whose permissions for other licensees extend to the entir"
  "e whole, and thus to each and every part regardless of who wrote it.\n\n"
  "Thus, it is not the intent of this section to claim rights or contest y"
  "our rights to work written entirely by you; rather, the intent is to ex"
  "ercise the right to control the distribution of derivative or collectiv"
  "e works based on the Library.\n\nIn addition, mere aggregation of anoth"
  "er work not based on the Library with the Library (or with a work based"
  " on the Library) on a volume of a storage or distribution medium does n"
  "ot bring the other work under the scope of this License.\n\n3. You may "
  "opt to apply the terms of the ordinary GNU General Public License inste"
  "ad of this License to a given copy of the Library. To do this, you must"
  " alter all the notices that refer to this License, so that they refer t"
  "o the ordinary GNU General Public License, version 2, instead of to thi"
  "s License. (If a newer version than version 2 of the ordinary GNU Gener"
  "al Public License has appeared, then you can specify that version inste"
  "ad if you wish.) Do not make any other change in these notices.\n\nOnce"
  " this change is made in a given copy, it is irreversible for that copy,"
  " so the ordinary GNU General Public License applies to all subsequent c"
  "opies and derivative works made from that copy.\n\nThis option is usefu"
  "l when you wish to copy part of the code of the Library into a program "
  "that is not a library.\n\n4. You may copy and distribute the Library (o"
  "r a portion or derivative of it, under Section 2) in object code or exe"
  "cutable form under the terms of Sections 1 and 2 above provided that yo"
  "u accompany it with the complete corresponding machine-readable source "
  "code, which must be distributed under the terms of Sections 1 and 2 abo"
  "ve on a medium customarily used for software interchange.\n\nIf distrib"
  "ution of object code is made by offering access to copy from a designat"
  "ed place, then offering equivalent access to copy the source code from "
  "the same place satisfies the requirement to distribute the source code,"
  " even though third parties are not compelled to copy the source along w"
  "ith the object code.\n\n5. A program that contains no derivative of any"
  " portion of the Library, but is designed to work with the Library by be"
  "ing compiled or linked with it, is called a \"work that uses the Librar"
  "y\". Such a work, in isolation, is not a derivative work of the Library"
  ", and therefore falls outside the scope of this License.\n\nHowever, li"
  "nking a \"work that uses the Library\" with the Library creates an exec"
  "utable that is a derivative of the Library (because it contains portion"
  "s of the Library), rather than a \"work that uses the library\". The ex"
  "ecutable is therefore covered by this License. Section 6 states terms f"
  "or distribution of such executables.\n\nWhen a \"work that uses the Lib"
  "rary\" uses material from a header file that is part of the Library, th"
  "e object code for the work may be a derivative work of the Library even"
  " though the source code is not. Whether this is true is especially sign"
  "ificant if the work can be linked without the Library, or if the work i"
  "s itself a library. The threshold for this to be true is not precisely "
  "defined by law.\n\nIf such an object file uses only numerical parameter"
  "s, data structure layouts and accessors, and small macros and small inl"
  "ine functions (ten lines or less in length), then the use of the object"
  " file is unrestricted, regardless of whether it is legally a derivative"
  " work. (Executables containing this object code plus portions of the Li"
  "brary will still fall under Section 6.)\n\nOtherwise, if the work is a "
  "derivative of the Library, you may distribute the object code for the w"
  "ork under the terms of Section 6. Any executables containing that work "
  "also fall under Section 6, whether or not they are linked directly with"
  " the Library itself.\n\n6. As an exception to the Sections above, you m"
  "ay also compile or link a \"work that uses the Library\" with the Libra"
  "ry to produce a work containing portions of the Library, and distribute"
  " that work under terms of your choice, provided that the terms permit m"
  "odification of the work for the customer\'s own use and reverse enginee"
  "ring for debugging such modifications.\n\nYou must give prominent notic"
  "e with each copy of the work that the Library is used in it and that th"
  "e Library and its use are covered by this License. You must supply a co"
  "py of this License. If the work during execution displays copyright not"
  "ices, you must include the copyright notice for the Library among them,"
  " as well as a reference directing the user to the copy of this License."
  " Also, you must do one of these things:\n\n    * a) Accompany the work "
  "with the complete corresponding machine-readable source code for the Li"
  "brary including whatever changes were used in the work (which must be d"
  "istributed under Sections 1 and 2 above); and, if the work is an execut"
  "able linked with the Library, with the complete machine-readable \"work"
  " that uses the Library\", as object code and/or source code, so that th"
  "e user can modify the Library and then relink to produce a modified exe"
  "cutable containing the modified Library. (It is understood that the use"
  "r who changes the contents of definitions files in the Library will not"
  " necessarily be able to recompile the application to use the modified d"
  "efinitions.)\n    * b) Accompany the work with a written offer, valid f"
  "or at least three years, to give the same user the materials specified "
  "in Subsection 6a, above, for a charge no more than the cost of performi"
  "ng this distribution.\n    * c) If distribution of the work is made by "
  "offering access to copy from a designated place, offer equivalent acces"
  "s to copy the above specified materials from the same place.\n    * d) "
  "Verify that the user has already received a copy of these materials or "
  "that you have already sent this user a copy.\n\nFor an executable, the "
  "required form of the \"work that uses the Library\" must include any da"
  "ta and utility programs needed for reproducing the executable from it. "
  "However, as a special exception, the source code distributed need not i"
  "nclude anything that is normally distributed (in either source or binar"
  "y form) with the major components (compiler, kernel, and so on) of the "
  "operating system on which the executable runs, unless that component it"
  "self accompanies the executable.\n\nIt may happen that this requirement"
  " contradicts the license restrictions of other proprietary libraries th"
  "at do not normally accompany the operating system. Such a contradiction"
  " means you cannot use both them and the Library together in an executab"
  "le that you distribute.\n\n7. You may place library facilities that are"
  " a work based on the Library side-by-side in a single library together "
  "with other library facilities not covered by this License, and distribu"
  "te such a combined library, provided that the separate distribution of "
  "the work based on the Library and of the other library facilities is ot"
  "herwise permitted, and provided that you do these two things:\n\n    * "
  "a) Accompany the combined library with a copy of the same work based on"
  " the Library, uncombined with any other library facilities. This must b"
  "e distributed under the terms of the Sections above.\n    * b) Give pro"
  "minent notice with the combined library of the fact that part of it is "
  "a work based on the Library, and explaining where to find the accompany"
  "ing uncombined form of the same work.\n\n8. You may not copy, modify, s"
  "ublicense, link with, or distribute the Library except as expressly pro"
  "vided under this License. Any attempt otherwise to copy, modify, sublic"
  "ense, link with, or distribute the Library is void, and will automatica"
  "lly terminate your rights under this License. However, parties who have"
  " received copies, or rights, from you under this License will not have "
  "their licenses terminated so long as such parties remain in full compli"
  "ance.\n\n9. You are not required to accept this License, since you have"
  " not signed it. However, nothing else grants you permission to modify o"
  "r distribute the Library or its derivative works. These actions are pro"
  "hibited by law if you do not accept this License. Therefore, by modifyi"
  "ng or distributing the Library (or any work based on the Library), you "
  "indicate your acceptance of this License to do so, and all its terms an"
  "d conditions for copying, distributing or modifying the Library or work"
  "s based on it.\n\n10. Each time you redistribute the Library (or any wo"
  "rk based on the Library), the recipient automatically receives a licens"
  "e from the original licensor to copy, distribute, link with or modify t"
  "he Library subject to these terms and conditions. You may not impose an"
  "y further restrictions on the recipients\' exercise of the rights grant"
  "ed herein. You are not responsible for enforcing compliance by third pa"
  "rties to this License.\n\n11. If, as a consequence of a court judgment "
  "or allegation of patent infringement or for any other reason (not limit"
  "ed to patent issues), conditions are imposed on you (whether by court o"
  "rder, agreement or otherwise) that contradict the conditions of this Li"
  "cense, they do not excuse you from the conditions of this License. If y"
  "ou cannot distribute so as to satisfy simultaneously your obligations u"
  "nder this License and any other pertinent obligations, then as a conseq"
  "uence you may not distribute the Library at all. For example, if a pate"
  "nt license would not permit royalty-free redistribution of the Library "
  "by all those who receive copies directly or indirectly through you, the"
  "n the only way you could satisfy both it and this License would be to r"
  "efrain entirely from distribution of the Library.\n\nIf any portion of "
  "this section is held invalid or unenforceable under any particular circ"
  "umstance, the balance of the section is intended to apply, and the sect"
  "ion as a whole is intended to apply in other circumstances.\n\nIt is no"
  "t the purpose of this section to induce you to infringe any patents or "
  "other property right claims or to contest validity of any such claims; "
  "this section has the sole purpose of protecting the integrity of the fr"
  "ee software distribution system which is implemented by public license "
  "practices. Many people have made generous contributions to the wide ran"
  "ge of software distributed through that system in reliance on consisten"
  "t application of that system; it is up to the author/donor to decide if"
  " he or she is willing to distribute software through any other system a"
  "nd a licensee cannot impose that choice.\n\nThis section is intended to"
  " make thoroughly clear what is believed to be a consequence of the rest"
  " of this License.\n\n12. If the distribution and/or use of the Library "
  "is restricted in certain countries either by patents or by copyrighted "
  "interfaces, the original copyright holder who places the Library under "
  "this License may add an explicit geographical distribution limitation e"
  "xcluding those countries, so that distribution is permitted only in or "
  "among countries not thus excluded. In such case, this License incorpora"
  "tes the limitation as if written in the body of this License.\n\n13. Th"
  "e Free Software Foundation may publish revised and/or new versions of t"
  "he Library General Public License from time to time. Such new versions "
  "will be similar in spirit to the present version, but may differ in det"
  "ail to address new problems or concerns.\n\nEach version is given a dis"
  "tinguishing version number. If the Library specifies a version number o"
  "f this License which applies to it and \"any later version\", you have "
  "the option of following the terms and conditions either of that version"
  " or of any later version published by the Free Software Foundation. If "
  "the Library does not specify a license version number, you may choose a"
  "ny version ever published by the Free Software Foundation.\n\n14. If yo"
  "u wish to incorporate parts of the Library into other free programs who"
  "se distribution conditions are incompatible with these, write to the au"
  "thor to ask for permission. For software which is copyrighted by the Fr"
  "ee Software Foundation, write to the Free Software Foundation; we somet"
  "imes make exceptions for this. Our decision will be guided by the two g"
  "oals of preserving the free status of all derivatives of our free softw"
  "are and of promoting the sharing and reuse of software generally.\n\nNO"
  " WARRANTY\n\n15. BECAUSE THE LIBRARY IS LICENSED FREE OF CHARGE, THERE "
  "IS NO WARRANTY FOR THE LIBRARY, TO THE EXTENT PERMITTED BY APPLICABLE L"
  "AW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/O"
  "R OTHER PARTIES PROVIDE THE LIBRARY \"AS IS\" WITHOUT WARRANTY OF ANY K"
  "IND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IM"
  "PLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOS"
  "E. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE LIBRARY IS "
  "WITH YOU. SHOULD THE LIBRARY PROVE DEFECTIVE, YOU ASSUME THE COST OF AL"
  "L NECESSARY SERVICING, REPAIR OR CORRECTION.\n\n16. IN NO EVENT UNLESS "
  "REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT H"
  "OLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR REDISTRIBUTE THE LIBRAR"
  "Y AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENER"
  "AL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE"
  " OR INABILITY TO USE THE LIBRARY (INCLUDING BUT NOT LIMITED TO LOSS OF "
  "DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR TH"
  "IRD PARTIES OR A FAILURE OF THE LIBRARY TO OPERATE WITH ANY OTHER SOFTW"
  "ARE), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIB"
  "ILITY OF SUCH DAMAGES.</property></object><object class=\"GtkTextBuffer"
  "\" id=\"bsd-buffer\"><property name=\"text\">Redistribution and use in "
  "source and binary forms, with or without modification, are permitted pr"
  "ovided that the following conditions are met:\n\n1. Redistributions of "
  "source code must retain the above copyright notice, this list of condit"
  "ions and the following disclaimer.\n\n2. Redistributions in binary form"
  " must reproduce the above copyright notice, this list of conditions and"
  " the following disclaimer in the documentation and/or other materials p"
  "rovided with the distribution.\n\n3. Neither the name of the organizati"
  "on nor the names of its contributors may be used to endorse or promote "
  "products derived from this software without specific prior written perm"
  "ission.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTR"
  "IBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT"
  " NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS "
  "FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGH"
  "T HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL"
  ", SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMI"
  "TED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,"
  " OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY"
  " OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDIN"
  "G NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SO"
  "FTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</property></"
  "object><object class=\"GtkTextBuffer\" id=\"vendor-buffer\"/></interfac"
  "e>"
};

static const unsigned xfce_about_dialog_ui_length = 50017u;

